//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canvas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Canvas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v1/users/self/profile.
        /// </summary>
        internal static string API_GET_USER_PROFILE {
            get {
                return ResourceManager.GetString("API_GET_USER_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v1/courses/{0}/assignments.
        /// </summary>
        internal static string API_LIST_ASSIGNMENTS {
            get {
                return ResourceManager.GetString("API_LIST_ASSIGNMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v1/courses.
        /// </summary>
        internal static string API_LIST_COURSES {
            get {
                return ResourceManager.GetString("API_LIST_COURSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v1/courses/{0}/modules.
        /// </summary>
        internal static string API_LIST_MODULES {
            get {
                return ResourceManager.GetString("API_LIST_MODULES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v1/courses/{0}/users?enrollment_type=student&amp;page={1}&amp;per_page=50.
        /// </summary>
        internal static string API_LIST_USERS_STUDENT {
            get {
                return ResourceManager.GetString("API_LIST_USERS_STUDENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /api/v1/courses/{0}/users?enrollment_type=teacher.
        /// </summary>
        internal static string API_LIST_USERS_TEACHER {
            get {
                return ResourceManager.GetString("API_LIST_USERS_TEACHER", resourceCulture);
            }
        }
    }
}
